# my-backendconfig.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  securityPolicy:
    name: app-user-policy
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60

